workflow

diff --git a/.github/workflows/repository.yml b/.github/workflows/repository.yml
--- a/.github/workflows/repository.yml
+++ b/.github/workflows/repository.yml
@@ -1,5 +1,11 @@
 name: Repository
 
+env:
+  CUSTOM_BRANCH: main
+  VOID_BRANCH: master
+  TAG: action-${{ github.run_number }}
+  SHA: ${{ github.sha }}
+
 on:
   push:
     branches:
@@ -10,16 +16,11 @@ on:
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
 
-env:
-  TAG: action-${{ github.run_number }}
-  SHA: ${{ github.sha }}
-
 jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
     strategy:
-      fail-fast: false
       matrix:
         config:
           - { arch: x86_64 }
@@ -27,6 +28,7 @@ jobs:
     env:
       ARCH: ${{ matrix.config.arch }}
       XBPS_TARGET_ARCH: ${{ matrix.config.arch }}
+      PATH: "/opt/xbps/usr/bin:${{ env.PATH }}"
 
     steps:
       - name: Free Space
@@ -51,7 +53,7 @@ jobs:
       - name: Checkout GitHub Repository
         uses: actions/checkout@v4
         with:
-          ref: master
+          ref: ${{ env.VOID_BRANCH }}
 
       - name: Merge GitHub Repository
         working-directory: ${{ github.workspace }}
@@ -75,39 +77,31 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          export PATH="/opt/xbps/usr/bin:$PATH"
-
           LATEST_TAG_NAME=$(gh release view --json tagName --jq '.tagName')
-          LATEST_TAG_SHA=$(git rev-list --max-count=1 $LATEST_TAG_NAME || git rev-list --max-parents=0 main)
+          LATEST_TAG_SHA=$(git rev-list --max-count=1 $LATEST_TAG_NAME || git rev-list --max-parents=0 $CUSTOM_BRANCH)
 
           git diff-tree -r --no-renames --name-only --diff-filter=AM $LATEST_TAG_SHA $SHA -- 'srcpkgs/**' |
             cut -d/ -f 2 |
-            xargs ./xbps-src sort-dependencies |
-            tee /tmp/templates
+              xargs ./xbps-src sort-dependencies |
+                tee /tmp/templates
 
       - name: Bootstrap xbps-src
         working-directory: ${{ github.workspace }}
         run: |
-          export PATH="/opt/xbps/usr/bin:$PATH"
-
           ./xbps-src -m masterdir-$ARCH -A $ARCH binary-bootstrap
 
       - name: Build Packages
         working-directory: ${{ github.workspace }}
         run: |
-          export PATH="/opt/xbps/usr/bin:$PATH"
-
           pkgs=$(cat /tmp/templates)
 
           for pkg in ${pkgs}; do
-            ./xbps-src -1 -j$(nproc) -m masterdir-$ARCH pkg "$pkg" || true
+            ./xbps-src -1 -j$(nproc) -m masterdir-$ARCH pkg "$pkg" || echo "Failed to build $pkg"
           done
 
       - name: Cleanup Repository
         working-directory: ${{ github.workspace }}/hostdir/binpkgs
         run: |
-          export PATH="/opt/xbps/usr/bin/:$PATH"
-
           xbps-rindex --remove-obsoletes $PWD
           xbps-rindex --clean $PWD
 
@@ -117,8 +111,6 @@ jobs:
           PRIVKEY: ${{ secrets.PRIVKEY }}
           XBPS_PASSPHRASE: ${{ secrets.PASSPHRASE }}
         run: |
-          export PATH="/opt/xbps/usr/bin/:$PATH"
-
           echo "$PRIVKEY" > privkey.pem
 
           xbps-rindex --privkey privkey.pem --sign --signedby "GitHub Actions" $PWD || true
@@ -149,7 +141,7 @@ jobs:
       - name: Merge Artifacts
         run: |
           mkdir merge
-          cp --recursive --verbose repodata/*/* merge
+          cp --verbose repodata/*/* merge
 
       - name: SHA256
         working-directory: merge
